### PR TITLE
Fix https://github.com/boostorg/lockfree/issues/35

### PR DESCRIPTION
**Pull request by austin-beer**
* Change runtime asserts to compile-time asserts
* Improve documentation for when capacity should be specified

### CODE REVIEW

**Comment by timblechmann** [comment]
it basically reverts 505c1c04c18939cfd8fbf58386230ee78f4549ad ... iirc this patch would prevent the classes from being externally instantiated.

afaict the proper way to go is to use `enable_if`

**Comment by timblechmann** [comment]
could you separate out the doc strings from the assertions? i'm happy to merge that part

**Comment by austin-beer** [comment]
Closing and re-opening PR to re-trigger CI builds

**Comment by austin-beer** [comment]
The build failures are only with clang, and appear to be unrelated to changes in this PR, so I think it can still be merged.

**Comment by austin-beer** [comment]
The previous commit fixed one of the two CI failures (it fixed clang on linux with libstdc++).

**Comment by timblechmann** [comment]
thanks a lot, also for the CI failure fix!

**Pull request merged**
