### PR TITLE
minimal changes to allow single move only values to be pushed and poped

### PR DESCRIPTION
**Pull request by tnovotny**
I have tried to keep the changes minimal.

### CODE REVIEW

**Comment by tnovotny** [comment]
Any feedback would be appreciated.

**Comment by tnovotny** [comment]
@timblechmann any feedback appreciated.

**Comment by timblechmann** [comment]
let's focus on #31 (this one breaks c++98 compatibility btw)

**Comment by tnovotny** [comment]
@timblechmann this should not be closed as this PR enables different things than [#31](https://github.com/boostorg/lockfree/pull/31). I think after over a year of waiting you should invest more time than to just close it. This one is not 'as developed' because it has received NO feedback.

**Comment by tnovotny** [comment]
> this one breaks c++98 compatibility btw

@timblechmann I don't think that's an argument. Move-able and move-only types added after c++98 really broke lock_free as it does not support them and its been 6 years.

**Comment by timblechmann** [comment]
@tnovotny some projects are bound to older compilers for various reasons. new boost libraries may choose not to support them, but older libraries should not fail to compile after a library update. if new functionality is added, it will have to be guarded by the corresponding config macros.

if you're improving the PR to make it compatible with c++98 (i'm fine with just not supporting movable types rather than using boost's move emulation), i'm more than happy to merge this PR and close the other one.

**Comment by tnovotny** [comment]
@timblechmann I'm not a versed boost-developer, so a quick question. Should I use the `BOOST_NO_CXX11_RVALUE_REFERENCES` macro for this or is there a better alternative?

**Comment by timblechmann** [comment]
@tnovotny yes `BOOST_NO_CXX11_RVALUE_REFERENCES` is probably the way to go. also for type traits, it would be safest to use the boost versions (or introduce a compatibility layer as i've done for the atomic data structures)

**Comment by tnovotny** [comment]
Since this one was closed i added an updated PR as version as [#41](https://github.com/boostorg/lockfree/pull/41).

**Pull request closed without merging**
